name: Backup code

on: 
  - push
  - delete
  - workflow_dispatch

jobs:
  sync:
    uses: kkp-dfs/dime-github-actions-workflows/.github/workflows/backup-sync.yml@main
    secrets:
      target-token: ${{ secrets.GL_ACCESS_TOKEN }}