name: Backup code

on: 
  push:
      branches:
        - main
        - 'release/**'
      tags:
        - '**'
  # - delete
  workflow_dispatch:

jobs:
  sync:
    uses: kkp-dfs/dime-github-actions-workflows/.github/workflows/backup-sync.yml@main
    secrets: inherit
